version: '3.2'

services:
  server-ffa:
    build:
      context: ./OgarII/app
    ports:
      - 127.0.0.1:3010:443
    volumes:
      - ./ffa-settings:/home/node/app/settings

  server-teams:
    build:
      context: ./OgarII/app
    ports:
      - 127.0.0.1:3011:443
    volumes:
      - ./teams-settings:/home/node/app/settings

  server-lms:
    build:
      context: ./OgarII/app
    ports:
      - 127.0.0.1:3012:443
    volumes:
      - ./lms-settings:/home/node/app/settings

  client:
    build:
      context: ./Cigar2/app
    ports:
      - 127.0.0.1:3002:3000
